const projectData = {
    "en": {
        "title": "SMALL & BEAUTIFUL",
        "subtitle": "A Curated Chronicle of Profitable Side Projects (2017 - 2025)",
        "stats": {
            "years": "9+ Years",
            "revenue": "$500+",
            "team": "Solo Built"
        },
        "years": ["2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017"],
        "visBtn": "Visit Project",
        "projects": {
            "2025": [
                { "name": "Mojo", "url": "https://mojoapp.ai/", "img": "assets/img/placeholder.jpg", "tag": "Health", "rev": "$1,150+", "desc": "AI health feedback from Apple Health data.", "factors": ["Health Connect", "Proactive AI"] },
                { "name": "TryPixie", "url": "https://trypixie.com", "img": "assets/img/placeholder.jpg", "tag": "Fintech", "rev": "$500+", "desc": "Tax management for hiring your kids.", "factors": ["Tax Niche", "Family Business"] },
                { "name": "Escape Team", "url": "https://www.escape-team.com", "img": "assets/img/placeholder.jpg", "tag": "Gaming", "rev": "$1,000+", "desc": "Printable pen & paper escape games.", "factors": ["Viral Group Activity", "Mission Editor"] },
                { "name": "Dead Chefs Society", "url": "https://www.deadchefssociety.com", "img": "assets/img/placeholder.jpg", "tag": "Community", "rev": "$126k/yr", "desc": "Curated dining events and society.", "factors": ["Real World Community", "Exclusive"] },
                { "name": "JustFaxOnline", "url": "https://justfaxonline.com", "img": "assets/img/placeholder.jpg", "tag": "Utility", "rev": "$500+", "desc": "Simple online faxing without accounts.", "factors": ["No-Sign-Up", "Pay-Per-Use"] },
                { "name": "AliveAi", "url": "https://aliveai.app", "img": "assets/img/placeholder.jpg", "tag": "AI", "rev": "$500+", "desc": "On-platform AI video generation.", "factors": ["GenAI Trend", "Strict Moderation"] },
                { "name": "Filestash", "url": "https://filestash.app", "img": "assets/img/placeholder.jpg", "tag": "DevTools", "rev": "Profitable", "desc": "Web-based file manager for any backend.", "factors": ["Open Source Core", "Enterprise Plugins"] },
                { "name": "Shepherd", "url": "https://shepherd.com", "img": "assets/img/placeholder.jpg", "tag": "Media", "rev": "Growing", "desc": "Book discovery via author picks.", "factors": ["SEO", "Author Interviews"] },
                { "name": "Repth", "url": "https://www.repth.com", "img": "assets/img/placeholder.jpg", "tag": "Fitness", "rev": "B2B", "desc": "Automated coaching logic licensing.", "factors": ["B2B Pivot", "Free for Users"] },
                { "name": "LeetArxiv", "url": "https://leetarxiv.substack.com", "img": "assets/img/placeholder.jpg", "tag": "Education", "rev": "Niche", "desc": "Math & Code research summary.", "factors": ["Niche Audience", "Substack"] },
                { "name": "CodeApprove", "url": "https://codeapprove.com", "img": "assets/img/placeholder.jpg", "tag": "DevTools", "rev": "SaaS", "desc": "Code review UI for GitHub.", "factors": ["GitHub Integration", "UX Focus"] },
                { "name": "You Don't Need JS", "url": "https://theosoti.com/you-dont-need-js/", "img": "assets/img/placeholder.jpg", "tag": "Education", "rev": "$500/mo", "desc": "Book about modern HTML & CSS.", "factors": ["Info Product", "No-JS Trend"] },
                { "name": "ShoppingScraper", "url": "https://shoppingscraper.com", "img": "assets/img/placeholder.jpg", "tag": "API", "rev": "SaaS", "desc": "EAN/GTIN to product data API.", "factors": ["E-commerce Data", "API First"] },
                { "name": "FindBoxes", "url": "https://www.findboxes.co", "img": "assets/img/placeholder.jpg", "tag": "SaaS", "rev": "$300/mo", "desc": "Inventory management for AV companies.", "factors": ["Niche B2B", "Vertical SaaS"] },
                { "name": "OnlyRecipe", "url": "https://onlyrecipeapp.com", "img": "assets/img/placeholder.jpg", "tag": "Utility", "rev": "$500+", "desc": "Simple recipe manager without clutter.", "factors": ["User Experience", "Declutter"] },
                { "name": "bewCloud", "url": "https://bewcloud.com", "img": "assets/img/placeholder.jpg", "tag": "DevTools", "rev": "$500+", "desc": "Simpler Nextcloud alternative.", "factors": ["Open Source", "Grant Funded"] },
                { "name": "Half Lemons", "url": "https://halflemons.com", "img": "assets/img/placeholder.jpg", "tag": "iOS App", "rev": "Freemium", "desc": "Recipes based on ingredients you have.", "factors": ["Mobile App", "Food Waste"] },
                { "name": "Abot", "url": "https://abot.app", "img": "assets/img/placeholder.jpg", "tag": "SaaS", "rev": "$2k/mo", "desc": "Anonymous feedback & polls for Slack.", "factors": ["Slack App", "Team Culture"] },
                { "name": "PickYourPhotos", "url": "https://pickyour.photos", "img": "assets/img/placeholder.jpg", "tag": "SaaS", "rev": "$790/mo", "desc": "Photo selection tool for photographers.", "factors": ["LatAm Market", "Vertical Tool"] },
                { "name": "SaveForLater", "url": "https://saveforlater.pro", "img": "assets/img/placeholder.jpg", "tag": "Utility", "rev": "New", "desc": "AI-powered bookmark manager.", "factors": ["AI Curation", "Productivity"] },
                { "name": "StockEvents", "url": "https://stockevents.app", "img": "assets/img/placeholder.jpg", "tag": "Fintech", "rev": "Profitable", "desc": "Comprehensive global portfolio tracker.", "factors": ["Mobile First", "Data Viz"] },
                { "name": "Olly", "url": "https://olly.bot", "img": "assets/img/placeholder.jpg", "tag": "AI", "rev": "$500+", "desc": "AI assistant integration for iMessage.", "factors": ["Messaging Integration", "Consumer AI"] },
                { "name": "Smitten", "url": "https://smittenstories.com", "img": "assets/img/placeholder.jpg", "tag": "Media", "rev": "Paywall", "desc": "Erotic story generator for couples.", "factors": ["Niche Content", "AI Gen"] },
                { "name": "HappyBara", "url": "https://happybara.io", "img": "assets/img/placeholder.jpg", "tag": "SaaS", "rev": "Portfolio", "desc": "Suite of productivity apps for Slack.", "factors": ["Micro-SaaS Strategy", "Slack Ecosystem"] },
                { "name": "TrendyZip", "url": "https://trendyzip.com", "img": "assets/img/placeholder.jpg", "tag": "Data", "rev": "$5/report", "desc": "Home sale trend reports for buyers.", "factors": ["Real Estate Data", "Micro-Transaction"] },
                { "name": "Replayer", "url": "https://www.replayer.online", "img": "assets/img/placeholder.jpg", "tag": "Education", "rev": "SaaS", "desc": "Browser-based music practice tool.", "factors": ["Music Ed", "Web Audio"] }
            ],
            "2024": [
                { "name": "LightNote", "url": "https://lightnote.co", "img": "assets/img/2024_lightnote.png", "tag": "Education", "rev": "$1,000+", "desc": "Interactive music theory learning platform.", "factors": ["Organic growth", "Added PayPal support"] },
                { "name": "Label LIVE", "url": "https://label.live", "img": "assets/img/2024_labellive.png", "tag": "SaaS", "rev": "5-6 Figures", "desc": "Barcode labeling for Mac/Windows.", "factors": ["Hardware bundle", "Niche expert"] },
                { "name": "OnlineOrNot", "url": "https://onlineornot.com", "img": "assets/img/2024_onlineornot.png", "tag": "DevTools", "rev": "$500+", "desc": "Uptime monitoring for APIs.", "factors": ["Deep documentation", "Human support"] },
                { "name": "PasteMaps", "url": "https://pastmaps.com", "img": "assets/img/2024_pastmaps.png", "tag": "Data", "rev": "Growing", "desc": "Historical maps digitization.", "factors": ["Unique data", "Niche hobby"] },
                { "name": "ExploreHere", "url": "https://explorehere.app", "img": "assets/img/2024_explorehere.png", "tag": "Travel", "rev": "<$1,000", "desc": "Passive adventure guide.", "factors": ["AI context", "Travel niche"] },
                { "name": "Grubbux", "url": "https://grubbux.com", "img": "assets/img/2024_grubbux.jpg", "tag": "Fintech", "rev": "Event-based", "desc": "Festival food currency system.", "factors": ["Data driven", "Fraud prevention"] },
                { "name": "Online Solitaire", "url": "https://solitaire.online", "img": "assets/img/2024_onlinesolitaire.jpg", "tag": "Gaming", "rev": "$1,000+", "desc": "High traffic web game.", "factors": ["SEO focused", "Ad revenue"] },
                { "name": "Typing Test", "url": "https://typingscat.com", "img": "assets/img/2024_typingtest.jpg", "tag": "Utility", "rev": "$500+", "desc": "Typing speed benchmark.", "factors": ["Tool based SEO", "Education market"] },
                { "name": "SqlTool", "url": "https://sqltool.io", "img": "assets/img/2024_sqltool.jpg", "tag": "DevTools", "rev": "$500+", "desc": "Database client in browser.", "factors": ["Privacy first", "UX centered"] },
                { "name": "Simple Analytics", "url": "https://simpleanalytics.com", "img": "assets/img/2024_simpleanalytics.jpg", "tag": "Analytics", "rev": "Scaling", "desc": "Privacy-first web analytics.", "factors": ["Anti-Google", "GDPR compliance"] }
            ],
            "2023": [
                { "name": "KTool", "url": "https://ktool.io", "img": "assets/img/2023_ktool.png", "tag": "Productivity", "rev": "$1k+", "desc": "Web to Kindle delivery.", "factors": ["Kindle niche", "Digital wellness"] },
                { "name": "Magic Lasso", "url": "https://magiclasso.co", "img": "assets/img/2023_magiclasso.png", "tag": "Utility", "rev": "$1k+", "desc": "Safari Ad blocker.", "factors": ["Apple ecosystem", "Reliability"] },
                { "name": "Typenine", "url": "https://typenineapp.com", "img": "assets/img/2023_typenine.jpg", "tag": "iOS App", "rev": "$500+", "desc": "T9 Keyboard for iPhone.", "factors": ["Nostalgia", "Design"] },
                { "name": "Mockup tool", "url": "https://mockup.io", "img": "assets/img/2023_mockuptool.jpg", "tag": "Design", "rev": "$500+", "desc": "Quick device mockups.", "factors": ["Designer workflow", "Speed"] },
                { "name": "Form Tool", "url": "https://formtool.com", "img": "assets/img/2023_formtool.jpg", "tag": "SaaS", "rev": "$1k+", "desc": "Simple form builder.", "factors": ["Low friction", "Integrations"] },
                { "name": "Screenshot API", "url": "https://screenshotapi.net", "img": "assets/img/2023_screenshotapi.jpg", "tag": "API", "rev": "$2k+", "desc": "Automated web screenshots.", "factors": ["Developer focus", "Reliability"] },
                { "name": "Monitoring Tool", "url": "https://checklyhq.com", "img": "assets/img/2023_monitoringtool.jpg", "tag": "DevOps", "rev": "Scaling", "desc": "Active monitoring.", "factors": ["Modern stack", "Speed"] },
                { "name": "Personal Finance", "url": "https://lunchmoney.app", "img": "assets/img/2023_personalfinance.jpg", "tag": "Fintech", "rev": "$5k+", "desc": "Modern budgeting.", "factors": ["UI/UX", "Solo build"] },
                { "name": "Job Board", "url": "https://remoteok.com", "img": "assets/img/2023_jobboard.jpg", "tag": "Jobs", "rev": "Huge", "desc": "Remote work listings.", "factors": ["SEO", "Digital nomad"] },
                { "name": "Email Tool", "url": "https://emailoctopus.com", "img": "", "tag": "Marketing", "rev": "Scaling", "desc": "Affordable email marketing.", "factors": ["SES integration", "Price"] }
            ],
            "2022": [
                { "name": "Linkz.ai", "url": "https://linkz.ai", "img": "assets/img/2022_linkz.png", "tag": "SaaS", "rev": "$500+", "desc": "Hyperlink auto-previews.", "factors": ["Wikipedia style", "Engagement"] },
                { "name": "Invisible Calendar", "url": "https://shop.invisible-computers.com", "img": "assets/img/2022_invisible.png", "tag": "Hardware", "rev": "$500+", "desc": "E-paper calendar for Google.", "factors": ["Anti-distraction", "Niche design"] },
                { "name": "FPGA Jobs", "url": "https://fpga.rtl.jobs", "img": "", "tag": "Jobs", "rev": "$500+", "desc": "Niche chip design jobs.", "factors": ["Extreme niche", "High value"] },
                { "name": "MessageDuck", "url": "https://messageduck.com", "img": "assets/img/2022_messageduck.jpg", "tag": "Marketing", "rev": "$500+", "desc": "SMS data marketing.", "factors": ["Automation", "Direct data"] },
                { "name": "Bodyweight Fitness", "url": "https://fitloop.co", "img": "assets/img/2022_bodyweightfitness.jpg", "tag": "Fitness", "rev": "$1k+", "desc": "Minimalist workout coach.", "factors": ["Reddit roots", "Simple UI"] },
                { "name": "Genetic Tool", "url": "https://omgenomics.com/circa", "img": "", "tag": "Science", "rev": "B2B", "desc": "Genomic sequence plotting.", "factors": ["Scientific niche", "Academia"] },
                { "name": "Japan Learner", "url": "https://patreon.com", "img": "", "tag": "Education", "rev": "$1.3k+", "desc": "Niche language content.", "factors": ["Patreon model", "Community"] },
                { "name": "Course Platform", "url": "https://podia.com", "img": "", "tag": "SaaS", "rev": "Scaling", "desc": "Sell courses easily.", "factors": ["Founder focus", "Simplicity"] },
                { "name": "Newsletter Service", "url": "https://ghost.org", "img": "", "tag": "Publishing", "rev": "Huge", "desc": "Open source newsletter.", "factors": ["Ownership", "Privacy"] },
                { "name": "API Gateway", "url": "https://tyk.io", "img": "", "tag": "DevTools", "rev": "Scaling", "desc": "Modern API management.", "factors": ["Open core", "Performance"] }
            ],
            "2021": [
                { "name": "Fitloop", "url": "https://fitloop.co", "img": "assets/img/2021_fitloop.jpg", "tag": "Fitness", "rev": "$1k+", "desc": "Bodyweight fitness app.", "factors": ["Personal need", "Maintenance"] },
                { "name": "Amazing Marvin", "url": "https://amazingmarvin.com", "img": "assets/img/2021_marvin.png", "tag": "Productivity", "rev": "$1k+", "desc": "Highly customizable task app.", "factors": ["Niche features", "Psychology"] },
                { "name": "CE for Babies", "url": "https://computerengineeringforbabies.com", "img": "assets/img/2021_cebabies.png", "tag": "Education", "rev": "$10k+", "desc": "Logic gate board book.", "factors": ["TikTok viral", "Tangible"] },
                { "name": "Down For Everyone", "url": "https://downforeveryoneorjustme.com", "img": "assets/img/2021_downforeveryone.jpg", "tag": "Utility", "rev": "$1k+", "desc": "Website status checker.", "factors": ["Brand SEO", "Domain name"] },
                { "name": "MicroAcquisitions", "url": "https://microacquisitions.com", "img": "assets/img/2021_microacquisitions.jpg", "tag": "Education", "rev": "$500+", "desc": "Buy small SaaS companies.", "factors": ["Market trend", "Expertise"] },
                { "name": "WebRender", "url": "https://webrender.io", "img": "", "tag": "DevTools", "rev": "$500+", "desc": "SEO rendering for SPAs.", "factors": ["Edge computing", "Fail-open"] },
                { "name": "Custom Fields", "url": "https://bonify.io", "img": "", "tag": "Shopify", "rev": "$5k+", "desc": "Shopify data extension.", "factors": ["App store SEO", "Support"] },
                { "name": "Circa", "url": "https://omgenomics.com/circa", "img": "", "tag": "Science", "rev": "$500+", "desc": "Genetic data viz.", "factors": ["Professional fee", "Niche"] },
                { "name": "Uptime Monitoring", "url": "https://updown.io", "img": "", "tag": "DevTools", "rev": "$5k+", "desc": "Lean status monitoring.", "factors": ["Pay-per-request", "UI"] },
                { "name": "Task Manager", "url": "https://todoist.com", "img": "", "tag": "Productivity", "rev": "Huge", "desc": "Clean task management.", "factors": ["Simplicity", "Multi-platform"] }
            ],
            "2020": [
                { "name": "UserTrack", "url": "https://usertrack.net", "img": "assets/img/2020_usertrack.jpg", "tag": "Analytics", "rev": "$500+", "desc": "Self-hosted heatmaps.", "factors": ["Privacy", "Self-hosted"] },
                { "name": "Panelbear", "url": "https://panelbear.com", "img": "assets/img/2020_panelbear.jpg", "tag": "Analytics", "rev": "$500+", "desc": "Fast website monitoring.", "factors": ["Performance", "Simplicity"] },
                { "name": "LogMyHours", "url": "https://logmyhours.com", "img": "", "tag": "Utility", "rev": "$1k+", "desc": "Clean time tracking.", "factors": ["Work/Use tool", "Rebuild"] },
                { "name": "BuyFunnyAprons", "url": "https://buyfunnyaprons.com", "img": "", "tag": "Ecommerce", "rev": "$500+", "desc": "Niche apron shop.", "factors": ["Search niche", "Physical"] },
                { "name": "SEO Tool", "url": "https://ahrefs.com", "img": "", "tag": "Marketing", "rev": "Huge", "desc": "Advanced SEO analysis.", "factors": ["Data", "Content"] },
                { "name": "PDF Tool", "url": "https://ilovepdf.com", "img": "", "tag": "Utility", "rev": "Huge", "desc": "Online PDF editor.", "factors": ["High volume", "SEO"] },
                { "name": "Screenshot Tool", "url": "https://snagit.com", "img": "", "tag": "Utility", "rev": "Huge", "desc": "Pro screen capture.", "factors": ["Legacy", "Features"] },
                { "name": "Email Marketing", "url": "https://convertkit.com", "img": "", "tag": "Saas", "rev": "Huge", "desc": "For creators.", "factors": ["Target audience", "Integrations"] },
                { "name": "Simple Analytics", "url": "https://simpleanalytics.com", "img": "", "tag": "Analytics", "rev": "$10k+", "desc": "No cookie analytics.", "factors": ["GDPR focus", "Privacy"] },
                { "name": "Plausible", "url": "https://plausible.io", "img": "", "tag": "Analytics", "rev": "$1M ARR", "desc": "Open source analytics.", "factors": ["Transparency", "Speed"] }
            ],
            "2019": [
                { "name": "Fine Word Clocks", "url": "https://finewordclocks.com", "img": "assets/img/2019_finewordclocks.jpg", "tag": "Hardware", "rev": "$500+", "desc": "Artistic word clocks.", "factors": ["Gifts", "Craftsmanship"] },
                { "name": "DiskPrices", "url": "https://diskprices.com", "img": "assets/img/2019_diskprices.png", "tag": "Affiliate", "rev": "$1k+", "desc": "Hard drive price per GB.", "factors": ["Pure utility", "No style"] },
                { "name": "BattPrices", "url": "https://battprices.com", "img": "", "tag": "Affiliate", "rev": "$500+", "desc": "Battery pricing engine.", "factors": ["Utility", "Automation"] },
                { "name": "TinyTask", "url": "https://tinytask.net", "img": "assets/img/2019_tinytask.jpg", "tag": "Utility", "rev": "$500+", "desc": "Tiny macro recorder.", "factors": ["Small size", "Tool SEO"] },
                { "name": "GrepWin", "url": "https://tools.stefankueng.com/grepWin.html", "img": "", "tag": "DevTools", "rev": "Donation", "desc": "GUI for grep on Windows.", "factors": ["Open Source", "Stability"] },
                { "name": "Site Checker", "url": "https://validator.w3.org", "img": "", "tag": "Utility", "rev": "Free", "desc": "W3C Validation.", "factors": ["Standard", "Authority"] },
                { "name": "Niche Job Board", "url": "https://weworkremotely.com", "img": "", "tag": "Jobs", "rev": "Huge", "desc": "Remote work leader.", "factors": ["Pioneer", "Quality"] },
                { "name": "Course", "url": "https://refactoringui.com", "img": "", "tag": "Education", "rev": "Huge", "desc": "Design for devs.", "factors": ["Design expert", "Targeting"] },
                { "name": "Newsletter", "url": "https://morningbrew.com", "img": "", "tag": "Media", "rev": "Huge", "desc": "Daily business news.", "factors": ["Tone", "Engagement"] },
                { "name": "CSS Tool", "url": "https://css-tricks.com", "img": "", "tag": "Education", "rev": "Sale", "desc": "Frontend knowledge.", "factors": ["SEO", "Community"] }
            ],
            "2018": [
                { "name": "180 Fitness", "url": "https://180fitness.co.uk", "img": "", "tag": "Physical", "rev": "$3k+", "desc": "24/7 automated gym.", "factors": ["Low overhead", "Local SEO"] },
                { "name": "Vast.ai", "url": "https://vast.ai", "img": "assets/img/2018_vastai.png", "tag": "Cloud", "rev": "Scaling", "desc": "P2P GPU marketplace.", "factors": ["Ahead of AI boom", "Price"] },
                { "name": "MarketGod", "url": "https://discord.gg", "img": "assets/img/2018_marketgod.jpg", "tag": "Finance", "rev": "$1k+", "desc": "Trading signals Discord.", "factors": ["Direct value", "Results"] },
                { "name": "Audit tool", "url": "https://auditboard.com", "img": "", "tag": "B2B", "rev": "Huge", "desc": "Risk & Compliance SaaS.", "factors": ["Enterpise need", "Workflow"] },
                { "name": "Status Page", "url": "https://statuspal.io", "img": "assets/img/2018_statuspage.jpg", "tag": "SaaS", "rev": "$1k+", "desc": "Incident communication.", "factors": ["Integrations", "Reliability"] },
                { "name": "Static Hosting", "url": "https://netlify.com", "img": "", "tag": "DevTools", "rev": "Huge", "desc": "Modern web hosting.", "factors": ["DX", "Automation"] },
                { "name": "VPN", "url": "https://mullvad.net", "img": "", "tag": "Privacy", "rev": "Huge", "desc": "Anonymous VPN.", "factors": ["Privacy ethic", "Security"] },
                { "name": "Proxy", "url": "https://brightdata.com", "img": "", "tag": "DevTools", "rev": "Huge", "desc": "Residential proxies.", "factors": ["Network size", "Enterprise"] },
                { "name": "Scraper", "url": "https://scrapingbee.com", "img": "", "tag": "API", "rev": "Scaling", "desc": "Headless browser API.", "factors": ["DX", "Solves pain"] },
                { "name": "Parser", "url": "https://parserr.com", "img": "", "tag": "Data", "rev": "$2k+", "desc": "Email to Excel parser.", "factors": ["Workflow automation", "Time"] }
            ],
            "2017": [
                { "name": "ServerCheck.in", "url": "https://servercheck.in", "img": "assets/img/2017_servercheck.png", "tag": "SaaS", "rev": "$500+", "desc": "Server monitoring service.", "factors": ["Cheap VPS", "Reliability"] },
                { "name": "Ansible Book", "url": "https://ansiblefordevops.com", "img": "assets/img/2017_ansiblebook.png", "tag": "Education", "rev": "$2k+", "desc": "Tech book on automation.", "factors": ["Self-publishing", "Niche"] },
                { "name": "Startup Ideas", "url": "https://nugget.one", "img": "assets/img/2017_startupideas.jpg", "tag": "Education", "rev": "$4k+", "desc": "Crowdsourced business ideas.", "factors": ["Community", "Inspiration"] },
                { "name": "Shopify App", "url": "https://bonify.io", "img": "assets/img/2017_shopifyapp.jpg", "tag": "Shopify", "rev": "$500+", "desc": "Merchant utility app.", "factors": ["Organic store traffic", "Need"] },
                { "name": "Solr Hosting", "url": "https://hostedapachesolr.com", "img": "", "tag": "Infrastructure", "rev": "$1k+", "desc": "Managed Search servers.", "factors": ["Specialist tech", "B2B"] },
                { "name": "Tutor Market", "url": "https://gumtree.com.au", "img": "", "tag": "Physical", "rev": "$500+", "desc": "Local home tutoring.", "factors": ["Local presence", "Word of mouth"] },
                { "name": "Voice Call Club", "url": "https://castingcall.club", "img": "assets/img/2017_voicecallclub.jpg", "tag": "Community", "rev": "$1k+", "desc": "Voice actor network.", "factors": ["Network effect", "Niche"] },
                { "name": "Accounting Tutor", "url": "https://acct229.com", "img": "", "tag": "Education", "rev": "$500+", "desc": "University course aid.", "factors": ["Hyper-local", "Repeatable"] },
                { "name": "Subscription Tool", "url": "https://publir.com", "img": "", "tag": "Media", "rev": "Scaling", "desc": "Monetize content site.", "factors": ["Ad-blocker bypass", "UX"] },
                { "name": "Physio App", "url": "https://movewellapp.com", "img": "", "tag": "Health", "rev": "$500+", "desc": "Post-injury home PT.", "factors": ["Personal pain", "Niche"] }
            ]
        }
    },
    "cn": {
        "title": "小而美",
        "subtitle": "Hacker News 盈利副业精选编年史 (2017 - 2025)",
        "stats": {
            "years": "9年+ 洞察",
            "revenue": "月入 $500+",
            "team": "独立开发"
        },
        "years": ["2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017"],
        "visBtn": "访问项目",
        "projects": {
            "2025": [
                { "name": "Mojo", "url": "https://mojoapp.ai/", "img": "assets/img/placeholder.jpg", "tag": "健康", "rev": "月入 $1,150", "desc": "基于数据的 AI 健康反馈助手。", "factors": ["健康数据集成", "主动式 AI"] },
                { "name": "TryPixie", "url": "https://trypixie.com", "img": "assets/img/placeholder.jpg", "tag": "金融科技", "rev": "月入 $500+", "desc": "合规雇佣子女的税务管理工具。", "factors": ["税务利基", "家族企业"] },
                { "name": "Escape Team", "url": "https://www.escape-team.com", "img": "assets/img/placeholder.jpg", "tag": "游戏", "rev": "月入 $1,000+", "desc": "打印即玩的纸笔密室逃脱。", "factors": ["线下社交", "任务编辑器"] },
                { "name": "Dead Chefs Society", "url": "https://www.deadchefssociety.com", "img": "assets/img/placeholder.jpg", "tag": "社区", "rev": "年收 $126k", "desc": "精心策划的线下餐饮聚会。", "factors": ["真实社区", "独家体验"] },
                { "name": "JustFaxOnline", "url": "https://justfaxonline.com", "img": "assets/img/placeholder.jpg", "tag": "工具", "rev": "月入 $500+", "desc": "无需注册的极简在线传真。", "factors": ["免登录", "按次付费"] },
                { "name": "AliveAi", "url": "https://aliveai.app", "img": "assets/img/placeholder.jpg", "tag": "AI", "rev": "月入 $500+", "desc": "在线 AI 视频生成平台。", "factors": ["生成式 AI", "严格审核"] },
                { "name": "Filestash", "url": "https://filestash.app", "img": "assets/img/placeholder.jpg", "tag": "开发者工具", "rev": "盈利中", "desc": "支持多种后端的 Web 文件管理器。", "factors": ["开源核心", "企业插件"] },
                { "name": "Shepherd", "url": "https://shepherd.com", "img": "assets/img/placeholder.jpg", "tag": "媒体", "rev": "增长中", "desc": "基于作者推荐的图书发现平台。", "factors": ["SEO 内容", "作者访谈"] },
                { "name": "Repth", "url": "https://www.repth.com", "img": "assets/img/placeholder.jpg", "tag": "健身", "rev": "B2B 授权", "desc": "自动化教练逻辑授权服务。", "factors": ["B2B 转型", "用户免费"] },
                { "name": "LeetArxiv", "url": "https://leetarxiv.substack.com", "img": "assets/img/placeholder.jpg", "tag": "教育", "rev": "小众付费", "desc": "数学与代码前沿研究摘要。", "factors": ["硬核小众", "Substack"] },
                { "name": "CodeApprove", "url": "https://codeapprove.com", "img": "assets/img/placeholder.jpg", "tag": "开发者工具", "rev": "SaaS", "desc": "GitHub 增强代码审查界面。", "factors": ["GitHub 集成", "用户体验"] },
                { "name": "You Don't Need JS", "url": "https://theosoti.com/you-dont-need-js/", "img": "assets/img/placeholder.jpg", "tag": "教育", "rev": "月入 $500", "desc": "关于现代 HTML/CSS 开发的书籍。", "factors": ["知识付费", "反 JS 趋势"] },
                { "name": "ShoppingScraper", "url": "https://shoppingscraper.com", "img": "assets/img/placeholder.jpg", "tag": "接口", "rev": "SaaS", "desc": "EAN/GTIN 电商数据爬虫 API。", "factors": ["电商数据", "API 优先"] },
                { "name": "FindBoxes", "url": "https://www.findboxes.co", "img": "assets/img/placeholder.jpg", "tag": "SaaS", "rev": "月入 $300", "desc": "视听行业的库存管理工具。", "factors": ["利基 B2B", "垂直 SaaS"] },
                { "name": "OnlyRecipe", "url": "https://onlyrecipeapp.com", "img": "assets/img/placeholder.jpg", "tag": "工具", "rev": "月入 $500+", "desc": "极其简洁的无广食谱管理应用。", "factors": ["用户体验优化", "极简主义"] },
                { "name": "bewCloud", "url": "https://bewcloud.com", "img": "assets/img/placeholder.jpg", "tag": "开发者工具", "rev": "月入 $500+", "desc": "更轻量的 Nextcloud 替代品。", "factors": ["开源", "基金会资助"] },
                { "name": "Half Lemons", "url": "https://halflemons.com", "img": "assets/img/placeholder.jpg", "tag": "iOS 应用", "rev": "免费增值", "desc": "基于你现有食材生成食谱。", "factors": ["移动应用", "减少浪费"] },
                { "name": "Abot", "url": "https://abot.app", "img": "assets/img/placeholder.jpg", "tag": "SaaS", "rev": "月入 $2k", "desc": "Slack 团队匿名反馈与投票工具。", "factors": ["Slack 应用", "团队文化"] },
                { "name": "PickYourPhotos", "url": "https://pickyour.photos", "img": "assets/img/placeholder.jpg", "tag": "SaaS", "rev": "月入 $790", "desc": "专为摄影师设计的选片工具。", "factors": ["拉美市场", "垂直工具"] },
                { "name": "SaveForLater", "url": "https://saveforlater.pro", "img": "assets/img/placeholder.jpg", "tag": "工具", "rev": "新品", "desc": "AI 驱动的智能书签管理器。", "factors": ["AI 整理", "生产力"] },
                { "name": "StockEvents", "url": "https://stockevents.app", "img": "assets/img/placeholder.jpg", "tag": "金融科技", "rev": "盈利中", "desc": "全球投资组合与股息追踪应用。", "factors": ["移动优先", "数据可视化"] },
                { "name": "Olly", "url": "https://olly.bot", "img": "assets/img/placeholder.jpg", "tag": "AI", "rev": "月入 $500+", "desc": "iMessage 原生集成的 AI 助手。", "factors": ["消息集成", "消费者 AI"] },
                { "name": "Smitten", "url": "https://smittenstories.com", "img": "assets/img/placeholder.jpg", "tag": "媒体", "rev": "付费墙", "desc": "情侣互动的情色故事生成器。", "factors": ["成人利基", "AI 生成"] },
                { "name": "HappyBara", "url": "https://happybara.io", "img": "assets/img/placeholder.jpg", "tag": "SaaS", "rev": "产品矩阵", "desc": "Slack 生产力增强工具套件。", "factors": ["微SaaS矩阵", "Slack 生态"] },
                { "name": "TrendyZip", "url": "https://trendyzip.com", "img": "assets/img/placeholder.jpg", "tag": "数据", "rev": "单次 $5", "desc": "购房者房地产市场趋势报告。", "factors": ["房地产数据", "微交易"] },
                { "name": "Replayer", "url": "https://www.replayer.online", "img": "assets/img/placeholder.jpg", "tag": "教育", "rev": "SaaS", "desc": "浏览器端的音乐练习与回放工具。", "factors": ["音乐教育", "Web Audio"] }
            ],
            "2024": [
                { "name": "LightNote", "url": "https://lightnote.co", "img": "assets/img/2024_lightnote.png", "tag": "教育", "rev": "$1,000+", "desc": "交互式乐理学习平台。", "factors": ["自然增长", "增加 PayPal 支持"] },
                { "name": "Label LIVE", "url": "https://label.live", "img": "assets/img/2024_labellive.png", "tag": "SaaS", "rev": "5-6 位数", "desc": "Mac/Windows 条码打印软件。", "factors": ["硬件捆绑", "行业专家标签"] },
                { "name": "OnlineOrNot", "url": "https://onlineornot.com", "img": "assets/img/2024_onlineornot.png", "tag": "开发者工具", "rev": "月入 $500+", "desc": "API 在线监控工具。", "factors": ["保姆级文档", "人性化支持"] },
                { "name": "PasteMaps", "url": "https://pastmaps.com", "img": "assets/img/2024_pastmaps.png", "tag": "数据", "rev": "增长中", "desc": "历史地图数字化平台。", "factors": ["独特数据源", "小众爱好者"] },
                { "name": "ExploreHere", "url": "https://explorehere.app", "img": "assets/img/2024_explorehere.png", "tag": "旅行", "rev": "约 $1,000", "desc": "被动式探险向导。", "factors": ["AI 上下文感知", "旅行细分赛道"] },
                { "name": "Grubbux", "url": "https://grubbux.com", "img": "", "tag": "金融科技", "rev": "事件驱动", "desc": "音乐节食品代币系统。", "factors": ["数据驱动", "防欺诈"] },
                { "name": "在线扫雷", "url": "https://solitaire.online", "img": "", "tag": "游戏", "rev": "$1,000+", "desc": "高流量网页游戏。", "factors": ["极致 SEO", "广告分成"] },
                { "name": "打字测试", "url": "https://typingscat.com", "img": "", "tag": "工具", "rev": "$500+", "desc": "打字速度基准测试工具。", "factors": ["工具类 SEO", "教育市场"] },
                { "name": "SqlTool", "url": "https://sqltool.io", "img": "", "tag": "开发者工具", "rev": "$500+", "desc": "浏览器端数据库客户端。", "factors": ["隐私优先", "极简交互"] },
                { "name": "Simple Analytics", "url": "https://simpleanalytics.com", "img": "", "tag": "分析", "rev": "成长期", "desc": "隐私优先的 Web 分析。", "factors": ["反 Google 策略", "GDPR 合规"] }
            ],
            "2023": [
                { "name": "KTool", "url": "https://ktool.io", "img": "assets/img/2023_ktool.png", "tag": "效率", "rev": "$1k+", "desc": "网页内容推送 Kindle。", "factors": ["Kindle 利基市场", "数字健康"] },
                { "name": "Magic Lasso", "url": "https://magiclasso.co", "img": "assets/img/2023_magiclasso.png", "tag": "工具", "rev": "$1k+", "desc": "Safari 广告拦截器。", "factors": ["苹果生态位", "极高稳定性"] },
                { "name": "Typenine", "url": "https://typenineapp.com", "img": "", "tag": "iOS 应用", "rev": "$500+", "desc": "iPhone 上的 T9 键盘。", "factors": ["怀旧情结", "设计感"] },
                { "name": "Mockup tool", "url": "https://mockup.io", "img": "", "tag": "设计", "rev": "$500+", "desc": "快速设备样机生成。", "factors": ["设计师工作流", "极速生成"] },
                { "name": "表单工具", "url": "https://formtool.com", "img": "", "tag": "SaaS", "rev": "$1k+", "desc": "简单易用的表单构建器。", "factors": ["低进入门槛", "丰富集成"] },
                { "name": "截图 API", "url": "https://screenshotapi.net", "img": "", "tag": "接口", "rev": "$2k+", "desc": "自动化网页截图服务。", "factors": ["开发者导向", "稳定性"] },
                { "name": "监控工具", "url": "https://checklyhq.com", "img": "", "tag": "DevOps", "rev": "快速增长", "desc": "主动式 API 监控。", "factors": ["现代技术栈", "极致响应"] },
                { "name": "个人理财", "url": "https://lunchmoney.app", "img": "", "tag": "金融", "rev": "$5k+", "desc": "现代记账理财软件。", "factors": ["极致 UI/UX", "单兵作战"] },
                { "name": "招聘板", "url": "https://remoteok.com", "img": "", "tag": "招聘", "rev": "巨量", "desc": "远程办公职位列表。", "factors": ["SEO 统治力", "数字游民"] },
                { "name": "邮件工具", "url": "https://emailoctopus.com", "img": "", "tag": "营销", "rev": "成长期", "desc": "高性价比邮件营销。", "factors": ["基于 AWS SES", "价格优势"] }
            ],
            "2022": [
                { "name": "Linkz.ai", "url": "https://linkz.ai", "img": "assets/img/2022_linkz.png", "tag": "SaaS", "rev": "$500+", "desc": "超链接自动预览脚本。", "factors": ["维基百科风格", "提升留存"] },
                { "name": "隐形日历", "url": "https://shop.invisible-computers.com", "img": "assets/img/2022_invisible.png", "tag": "硬件", "rev": "$500+", "desc": "Google 墨水屏日历。", "factors": ["反干扰设计", "小众审度"] },
                { "name": "芯片招聘", "url": "https://fpga.rtl.jobs", "img": "", "tag": "招聘", "rev": "$500+", "desc": "FPGA 芯片设计招聘。", "factors": ["极端细分", "高客单价"] },
                { "name": "MessageDuck", "url": "https://messageduck.com", "img": "", "tag": "营销", "rev": "$500+", "desc": "短消息营销分析。", "factors": ["高度自动化", "实时数据"] },
                { "name": "自重健身", "url": "https://fitloop.co", "img": "", "tag": "健身", "rev": "$1k+", "desc": "极简家庭健身教练。", "factors": ["社区冷启动", "极简设计"] },
                { "name": "基因工具", "url": "https://omgenomics.com/circa", "img": "", "tag": "科学", "rev": "B2B", "desc": "基因序列绘图工具。", "factors": ["跨学科利基", "科研刚需"] },
                { "name": "日语学习", "url": "https://patreon.com", "img": "", "tag": "教育", "rev": "$1.3k+", "desc": "小众语言内容创作。", "factors": ["赞助模式", "忠诚社区"] },
                { "name": "课程平台", "url": "https://podia.com", "img": "", "tag": "SaaS", "rev": "成长期", "desc": "轻松售卖在线课程。", "factors": ["创始人精神", "操作直观"] },
                { "name": "邮件订阅", "url": "https://ghost.org", "img": "", "tag": "出版", "rev": "巨量", "desc": "开源邮件订阅系统。", "factors": ["内容所有权", "隐私策略"] },
                { "name": "API 网关", "url": "https://tyk.io", "img": "", "tag": "开发者工具", "rev": "快速增长", "desc": "现代 API 管理平台。", "factors": ["开源核心", "极高性能"] }
            ],
            "2021": [
                { "name": "Fitloop", "url": "https://fitloop.co", "img": "", "tag": "运动", "rev": "$1k+", "desc": "自重健身练习应用。", "factors": ["解决自身痛点", "维护极简"] },
                { "name": "Amazing Marvin", "url": "https://amazingmarvin.com", "img": "assets/img/2021_marvin.png", "tag": "效率", "rev": "$1k+", "desc": "高度可定制的任务软件。", "factors": ["定制化功能", "心理学导向"] },
                { "name": "婴儿计算机", "url": "https://computerengineeringforbabies.com", "img": "assets/img/2021_cebabies.png", "tag": "教育", "rev": "$10k+", "desc": "逻辑门电路纸板书。", "factors": ["短视频爆火", "真实触感"] },
                { "name": "宕机检查", "url": "https://downforeveryoneorjustme.com", "img": "", "tag": "工具", "rev": "$1k+", "desc": "网站在线状态检测。", "factors": ["品牌化 SEO", "极品域名"] },
                { "name": "小微收购", "url": "https://microacquisitions.com", "img": "", "tag": "教育", "rev": "$500+", "desc": "小微 SaaS 收购课程。", "factors": ["顺应风口", "专业背书"] },
                { "name": "WebRender", "url": "https://webrender.io", "img": "", "tag": "开发者工具", "rev": "$500+", "desc": "为 SPA 提供 SEO 渲染。", "factors": ["边缘计算", "断网降级"] },
                { "name": "自定义字段", "url": "https://bonify.io", "img": "", "tag": "Shopify", "rev": "$5k+", "desc": "Shopify 数据扩展插件。", "factors": ["商店应用 SEO", "重服务支持"] },
                { "name": "Circa", "url": "https://omgenomics.com/circa", "img": "", "tag": "科学", "rev": "$500+", "desc": "基因数据可视化。", "factors": ["专业付费授权", "极深护城河"] },
                { "name": "Uptime 监控", "url": "https://updown.io", "img": "", "tag": "开发者工具", "rev": "$5k+", "desc": "精炼的状态监控。", "factors": ["按请求计费", "精致 UI"] },
                { "name": "任务管理", "url": "https://todoist.com", "img": "", "tag": "效率", "rev": "巨量", "desc": "极简任务管理系统。", "factors": ["简洁无暇", "多平台同步"] }
            ],
            "2020": [
                { "name": "UserTrack", "url": "https://usertrack.net", "img": "", "tag": "分析", "rev": "$500+", "desc": "私有部署的热力图工具。", "factors": ["隐私敏感型", "自建方案"] },
                { "name": "Panelbear", "url": "https://panelbear.com", "img": "", "tag": "分析", "rev": "$500+", "desc": "急速网站监控体验。", "factors": ["极致性能", "简单易用"] },
                { "name": "工时记录", "url": "https://logmyhours.com", "img": "", "tag": "工具", "rev": "$1k+", "desc": "极简工时追踪工具。", "factors": ["自己也用", "迭代重构"] },
                { "name": "搞怪围裙", "url": "https://buyfunnyaprons.com", "img": "", "tag": "电商", "rev": "$500+", "desc": "趣味围裙垂直电商。", "factors": ["搜索长尾词", "实物产品"] },
                { "name": "SEO 工具", "url": "https://ahrefs.com", "img": "", "tag": "营销", "rev": "巨量", "desc": "专业 SEO 数据分析。", "factors": ["海量数据", "内容引流"] },
                { "name": "PDF 工具", "url": "https://ilovepdf.com", "img": "", "tag": "工具", "rev": "巨量", "desc": "在线 PDF 编辑处理器。", "factors": ["高频刚需", "强 SEO"] },
                { "name": "截图王", "url": "https://snagit.com", "img": "", "tag": "工具", "rev": "巨量", "desc": "专业屏幕采集套件。", "factors": ["长期口碑", "功能深度"] },
                { "name": "邮件营销", "url": "https://convertkit.com", "img": "", "tag": "SaaS", "rev": "巨量", "desc": "创作者专用邮件系统。", "factors": ["精准受众", "丰富集成"] },
                { "name": "简单分析", "url": "https://simpleanalytics.com", "img": "", "tag": "分析", "rev": "$10k+", "desc": "无 Cookie 隐私分析。", "factors": ["GDPR 刚需", "纯净体验"] },
                { "name": "Plausible", "url": "https://plausible.io", "img": "", "tag": "分析", "rev": "$1M ARR", "desc": "开源 Web 分析服务。", "factors": ["公开透明", "急速加载"] }
            ],
            "2019": [
                { "name": "文字时钟", "url": "https://finewordclocks.com", "img": "", "tag": "硬件", "rev": "$500+", "desc": "实木单词拼写时钟。", "factors": ["独家礼品", "手工匠心"] },
                { "name": "硬盘比价", "url": "https://diskprices.com", "img": "assets/img/2019_diskprices.png", "tag": "返利", "rev": "$1k+", "desc": "监控硬盘单位容量价。", "factors": ["极致实用", "零设计感"] },
                { "name": "电池比价", "url": "https://battprices.com", "img": "", "tag": "返利", "rev": "$500+", "desc": "电池价格分析引擎。", "factors": ["计算器型工具", "自动化"] },
                { "name": "TinyTask", "url": "https://tinytask.net", "img": "", "tag": "工具", "rev": "$500+", "desc": "极致小巧的宏记录器。", "factors": ["体积优势", "工具 SEO"] },
                { "name": "GrepWin", "url": "https://tools.stefankueng.com/grepWin.html", "img": "", "tag": "开发者工具", "rev": "捐赠", "desc": "Windows 上的 Grep 界面。", "factors": ["开源社区", "极致稳定"] },
                { "name": "代码校验", "url": "https://validator.w3.org", "img": "", "tag": "工具", "rev": "免费", "desc": "W3C 标准校验工具。", "factors": ["行业标准", "权威背书"] },
                { "name": "远程招聘板", "url": "https://weworkremotely.com", "img": "", "tag": "招聘", "rev": "巨量", "desc": "远程办公领头羊。", "factors": ["先行者优势", "高质量"] },
                { "name": "UI 课程", "url": "https://refactoringui.com", "img": "", "tag": "教育", "rev": "巨量", "desc": "为开发者提供 UI 指导。", "factors": ["行业大号", "精准打击"] },
                { "name": "晨报订阅", "url": "https://morningbrew.com", "img": "", "tag": "媒体", "rev": "巨量", "desc": "每日商业新闻摘要。", "factors": ["内容语调", "极高互动"] },
                { "name": "CSS Tricks", "url": "https://css-tricks.com", "img": "", "tag": "教育", "rev": "已收购", "desc": "前端开发知识库。", "factors": ["内容长效性", "社区属性"] }
            ],
            "2018": [
                { "name": "180 健身", "url": "https://180fitness.co.uk", "img": "", "tag": "物理", "rev": "$3k+", "desc": "全自动 24 小时健身房。", "factors": ["极低人力成本", "本地 SEO"] },
                { "name": "Vast.ai", "url": "https://vast.ai", "img": "assets/img/2018_vastai.png", "tag": "云服务", "rev": "成长期", "desc": "P2P GPU 算力市场。", "factors": ["踩中 AI 算力热点", "低价"] },
                { "name": "MarketGod", "url": "https://discord.gg", "img": "", "tag": "金融", "rev": "$1k+", "desc": "交易信号 Discord 服务。", "factors": ["提供直接价值", "战绩公开"] },
                { "name": "审计看板", "url": "https://auditboard.com", "img": "", "tag": "B2B", "rev": "巨量", "desc": "风险合规管理 SaaS。", "factors": ["企业刚需", "流程整合"] },
                { "name": "状态页面", "url": "https://statuspal.io", "img": "", "tag": "SaaS", "rev": "$1k+", "desc": "故障与维护通知平台。", "factors": ["多系统集成", "高可用性"] },
                { "name": "静态托管", "url": "https://netlify.com", "img": "", "tag": "开发工具", "rev": "巨量", "desc": "现代 Web 托管平台。", "factors": ["开发者体验", "自动化部署"] },
                { "name": "Mullvad VPN", "url": "https://mullvad.net", "img": "", "tag": "隐私", "rev": "巨量", "desc": "真正的匿名 VPN。", "factors": ["隐私原则", "品牌信任"] },
                { "name": "代理网络", "url": "https://brightdata.com", "img": "", "tag": "开发工具", "rev": "巨量", "desc": "住宅级代理网络。", "factors": ["网络规模", "企业级合规"] },
                { "name": "采集蜜蜂", "url": "https://scrapingbee.com", "img": "", "tag": "API", "rev": "成长期", "desc": "无头浏览器采集接口。", "factors": ["极简开发者体验", "解决痛点"] },
                { "name": "数据解析器", "url": "https://parserr.com", "img": "", "tag": "数据", "rev": "$2k+", "desc": "邮件自动转 Excel 工具。", "factors": ["工作流自动化", "省时利器"] }
            ],
            "2017": [
                { "name": "ServerCheck.in", "url": "https://servercheck.in", "img": "assets/img/2017_servercheck.png", "tag": "SaaS", "rev": "$500+", "desc": "极简服务器监控服务。", "factors": ["超廉价 VPS 节点", "稳定性"] },
                { "name": "Ansible 之书", "url": "https://ansiblefordevops.com", "img": "assets/img/2017_ansiblebook.png", "tag": "教育", "rev": "$2k+", "desc": "硬核自动化运维书籍。", "factors": ["独立出版", "领域权威"] },
                { "name": "想法集市", "url": "https://nugget.one", "img": "", "tag": "教育", "rev": "$4k+", "desc": "众包商业创意发掘平台。", "factors": ["社区属性", "持续灵感"] },
                { "name": "Shopify 插件", "url": "https://bonify.io", "img": "", "tag": "Shopify", "rev": "$500+", "desc": "针对特定商家的小工具。", "factors": ["商店内生流量", "强硬刚需"] },
                { "name": "Solr 托管", "url": "https://hostedapachesolr.com", "img": "", "tag": "基础架构", "rev": "$1k+", "desc": "管理型企业级搜索服务器。", "factors": ["垂直技术深耕", "B2B 属性"] },
                { "name": "家教平台", "url": "https://gumtree.com.au", "img": "", "tag": "物理", "rev": "$500+", "desc": "本地一对一上门家教。", "factors": ["本地化存在感", "口碑传播"] },
                { "name": "配音俱乐部", "url": "https://castingcall.club", "img": "", "tag": "社区", "rev": "$1k+", "desc": "声优与演员社交网络。", "factors": ["网络效应", "细分小众"] },
                { "name": "会计辅导", "url": "https://acct229.com", "img": "", "tag": "教育", "rev": "$500+", "desc": "大学会计课程辅助。", "factors": ["高物理壁垒", "极高复购率"] },
                { "name": "Publir", "url": "https://publir.com", "img": "", "tag": "媒体", "rev": "成长期", "desc": "内容网站订阅变现工具。", "factors": ["对抗广告拦截", "顺滑交互"] },
                { "name": "康复应用", "url": "https://movewellapp.com", "img": "", "tag": "健康", "rev": "$500+", "desc": "伤后家庭康复指导工具。", "factors": ["解决自身伤痛", "专业性"] }
            ]
        }
    }
};
